ruleset:   
  tag_support:    
    name: "Label issues as support"   
    events: [ issues ]    
    label: support    
    when:   
      - body contains "/\[\s?x\s?\] support/"
      - action = "opened"
